{% set name = "pdpyras" %}
{% set version = "4.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdpyras-{{ version }}.tar.gz
  sha256: 80e7ac165e0aefbaaa2354c0f707610a180e65c5619c3bdd5de7c22cafa2063b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - requests
    - urllib3

test:
  imports:
    - pdpyras
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pagerduty.github.io/pdpyras
  summary: PagerDuty REST API client
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/PagerDuty/pdpyras
  doc_url: https://pagerduty.github.io/pdpyras

extra:
  recipe-maintainers:
    - xylar
